# Generated by Django 5.2.3 on 2025-07-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sarten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
